### ISSUE TITLE
`dak.singletons` errors

### ISSUE THREAD

**Issue by masonproffitt** [dask-contrib/dask-awkward#252]
This is the non-dask version of what I'm trying to do (using [this file](https://github.com/iris-hep/func_adl_uproot/blob/4c1432057c84ffbe2628a271543201bde80cb01b/tests/vectors_tree_file.root)):

```python
>>> import uproot, awkward as ak, dask_awkward as dak
>>> a = uproot.open('func_adl_uproot/tests/vectors_tree_file.root:tree').arrays()
>>> step1 = ak.unzip(ak.combinations(a.float_vector_branch, 2, axis=1))[0]
>>> step1
<Array [[], [-7.7, -7.7, 8.8], []] type='3 * var * float32'>
>>> step2 = ak.singletons(step1, axis=1)
>>> step2
<Array [[], [[-7.7], ..., [8.8]], []] type='3 * var * var * float32'>
```

With the latest version of `dask-awkward` (`2023.4.2`), I get one of two errors trying to reproduce this. The first is:

```python
>>> da = uproot.dask('func_adl_uproot/tests/vectors_tree_file.root')
>>> dstep1 = dak.unzip(dak.combinations(da.float_vector_branch, 2, axis=1))[0]
>>> dstep1.compute()
<Array [[], [-7.7, -7.7, 8.8], []] type='3 * var * float32'>
>>> dstep2 = dak.singletons(step1, axis=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/iris-hep/src/dask-awkward/src/dask_awkward/lib/structure.py", line 729, in singletons
    return map_partitions(
  File "/home/user/iris-hep/src/dask-awkward/src/dask_awkward/lib/core.py", line 1467, in map_partitions
    npartitions=deps[0].npartitions,
IndexError: list index out of range
```

Interestingly, I get a different error if I try to do both steps in the same expression:

```python
>>> dsteps12 = dak.singletons(dak.unzip(dak.combinations(da.float_vector_branch, 2, axis=1))[0], axis=1)
>>> dsteps12.compute()
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/awkward/highlevel.py", line 948, in __getitem__
    out = self._layout[where]
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/awkward/contents/content.py", line 537, in __getitem__
    return self._getitem(where)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/awkward/contents/content.py", line 554, in _getitem
    return self._getitem_field(where)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/awkward/contents/recordarray.py", line 462, in _getitem_field
    return self.content(where)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/awkward/contents/recordarray.py", line 397, in content
    out = self.form_cls.content(self, index_or_field)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/awkward/forms/recordform.py", line 145, in content
    index = self.field_to_index(index_or_field)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/awkward/contents/recordarray.py", line 391, in field_to_index
    return self.form_cls.field_to_index(self, field)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/awkward/forms/recordform.py", line 124, in field_to_index
    raise ak._errors.FieldNotFoundError(
awkward._errors.FieldNotFoundError: no field 'float_vector_branch' in record with 1 fields

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/base.py", line 314, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/base.py", line 599, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/threaded.py", line 89, in get
    results = get_async(
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/local.py", line 511, in get_async
    raise_exception(exc, tb)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/local.py", line 319, in reraise
    raise exc
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/local.py", line 224, in execute_task
    result = _execute_task(task, data)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/optimization.py", line 990, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/awkward/highlevel.py", line 947, in __getitem__
    with ak._errors.SlicingErrorContext(self, where):
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/awkward/_errors.py", line 56, in __exit__
    self.handle_exception(exception_type, exception_value)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/awkward/_errors.py", line 66, in handle_exception
    raise self.decorate_exception(cls, exception)
awkward._errors.FieldNotFoundError: no field 'float_vector_branch' in record with 1 fields

This error occurred while attempting to slice

    <Array [{int_vector_branch: []}, ..., {...}] type='3 * {int_vector_bran...'>

with

    'float_vector_branch'
```

A `git bisect` shows that this commit (https://github.com/dask-contrib/dask-awkward/commit/541cb18999e1e20934c30f00fb2709acc103d681) introduced this error. Before that, this was working exactly the same as the plain `uproot`/`awkward` example.

If I try something similar without `uproot`, such as:

```python
>>> a = ak.Array([[{'b': 1, 'c': 2}, {'b': 3, 'c': 4}]])
>>> step1 = ak.unzip(ak.combinations(a.c, 2, axis=1))[0]
>>> step1
<Array [[2]] type='1 * var * int64'>
>>> step2 = ak.singletons(step1, axis=1)
>>> step2
<Array [[[2]]] type='1 * var * var * int64'>
```

then I can still reproduce the first error:

```python
>>> da = dak.from_awkward(a, 1)
>>> dstep1 = dak.unzip(dak.combinations(da.c, 2, axis=1))[0]
>>> dstep1.compute()
<Array [[2]] type='1 * var * int64'>
>>> dstep2 = dak.singletons(step1, axis=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/iris-hep/src/dask-awkward/src/dask_awkward/lib/structure.py", line 729, in singletons
    return map_partitions(
  File "/home/user/iris-hep/src/dask-awkward/src/dask_awkward/lib/core.py", line 1467, in map_partitions
    npartitions=deps[0].npartitions,
IndexError: list index out of range
```

but curiously not the second:

```python
>>> dsteps12 = dak.singletons(dak.unzip(dak.combinations(da.c, 2, axis=1))[0], axis=1)
>>> dsteps12.compute()
<Array [[[2]]] type='1 * var * var * int64'>
```

**Comment by martindurant** [comment]
If I had a file of the type you are playing with, I could trace this error better. The commit singled out was one of @lgray 's, if perhaps it's immediately obvious. My first thought, is that singletons don't by definition have partitions, so maybe they are being included in the optimisation logic where they shouldn't be (at the point where we select first partitions of everything for the typetracer run).

**Comment by lgray** [comment]
@masonproffitt for your example:
```python3
>>> da = dak.from_awkward(a, 1)
>>> dstep1 = dak.unzip(dak.combinations(da.c, 2, axis=1))[0]
>>> dstep1.compute()
<Array [[2]] type='1 * var * int64'>
>>> dstep2 = dak.singletons(step1, axis=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/iris-hep/src/dask-awkward/src/dask_awkward/lib/structure.py", line 729, in singletons
    return map_partitions(
  File "/home/user/iris-hep/src/dask-awkward/src/dask_awkward/lib/core.py", line 1467, in map_partitions
    npartitions=deps[0].npartitions,
IndexError: list index out of range
```
you are getting the `index list out of range` because you are passing `step1` into `dak.singletons(step1, axis=1)` as opposed to `dstep1` and since `step1` is not dask awkward there are no dask_awkward arrays to determine the number of partitions from.

**Comment by lgray** [comment]
For the uproot example you have not specified the tree to read from, so `uproot.dask`  is failing in the right way.

You need to do:
```python3
da = uproot.dask({'func_adl_uproot/tests/vectors_tree_file.root': 'tree'})
```

**Comment by lgray** [comment]
@martindurant  you can get the file here: https://github.com/iris-hep/func_adl_uproot/blob/master/tests/vectors_tree_file.root?raw=true

If I fix those typos and run I still get:
```
This error occurred while attempting to slice

    <Array [{int_vector_branch: []}, ..., {...}] type='3 * {int_vector_bran...'>

with

    'float_vector_branch'
```

If I apply the singletons work-around removal in https://github.com/dask-contrib/dask-awkward/pull/251 that's now possible from awkward 2.1.4 then this error goes away.

**Comment by martindurant** [comment]
> If I apply the singletons work-around removal in https://github.com/dask-contrib/dask-awkward/pull/251 that's now possible from awkward 2.1.4 then this error goes away.

OK, well let's mark that PR as closing this issue then!

**Comment by masonproffitt** [comment]
> @masonproffitt for your example:
> 
> ```python
> >>> da = dak.from_awkward(a, 1)
> >>> dstep1 = dak.unzip(dak.combinations(da.c, 2, axis=1))[0]
> >>> dstep1.compute()
> <Array [[2]] type='1 * var * int64'>
> >>> dstep2 = dak.singletons(step1, axis=1)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/user/iris-hep/src/dask-awkward/src/dask_awkward/lib/structure.py", line 729, in singletons
>     return map_partitions(
>   File "/home/user/iris-hep/src/dask-awkward/src/dask_awkward/lib/core.py", line 1467, in map_partitions
>     npartitions=deps[0].npartitions,
> IndexError: list index out of range
> ```
> 
> you are getting the `index list out of range` because you are passing `step1` into `dak.singletons(step1, axis=1)` as opposed to `dstep1` and since `step1` is not dask awkward there are no dask_awkward arrays to determine the number of partitions from.

Ah, yes, true. That explains why that it didn't show up in the non-uproot case.

> For the uproot example you have not specified the tree to read from, so `uproot.dask` is failing in the right way.
> 
> You need to do:
> 
> ```python
> da = uproot.dask({'func_adl_uproot/tests/vectors_tree_file.root': 'tree'})
> ```

No, you don't have to specify the tree name. It works fine without it:
```python
>>> da = uproot.dask('func_adl_uproot/tests/vectors_tree_file.root')
>>> da.compute()
<Array [{int_vector_branch: [], ...}, ...] type='3 * {int_vector_branch: va...'>
```

> @martindurant you can get the file here: https://github.com/iris-hep/func_adl_uproot/blob/master/tests/vectors_tree_file.root?raw=true
> 
> If I fix those typos and run I still get:
> 
> ```
> This error occurred while attempting to slice
> 
>     <Array [{int_vector_branch: []}, ..., {...}] type='3 * {int_vector_bran...'>
> 
> with
> 
>     'float_vector_branch'
> ```
> 
> If I apply the singletons work-around removal in #251 that's now possible from awkward 2.1.4 then this error goes away.

Yeah, that branch seems to work.

**Comment by lgray** [comment]
> No, you don't have to specify the tree name. It works fine without it:

Ah didn't know that, and it seems counter to their usual practice of having to be quite explicit about what you want to do.
I have a feeling this shorthand is accidental and should be removed.

**Comment by masonproffitt** [comment]
It's not accidental; there was a long discussion about this (among other file/tree specification issues) a few years ago. It only works if there is exactly one tree in the file (https://github.com/scikit-hep/uproot5/issues/79#issuecomment-681054061).

**Comment by lgray** [comment]
Very well. My opinion is it doesn't fit with the rest of the interface.

**Comment by masonproffitt** [comment]
fixed by #251
