### ISSUE TITLE
Feature request: support for ak.to_rdataframe

### ISSUE THREAD

**Issue by jcatmore** [dask-contrib/dask-awkward#370]
Hello,

for the purposes of using C++ functions with Awkward arrays as arguments (called from the Python environment) it seems the recommendation is to use RDataFrame as the "hook" (and with RDataFrame then it is then trivial to call C++ methods). This is demonstrated (e.g.) [here](https://github.com/ianna/PyHep2022/tree/main) and described in [this talk](https://indico.fnal.gov/event/23628/contributions/240305/attachments/154908/201609/Awkward%20Arrays%20to%20RDataFrame%20and%20back-10.05.2022.pdf).

For Dask-awkward, the relevant method doesn't seem to exist:

`
AttributeError: module 'dask_awkward' has no attribute 'to_rdataframe'
`

Would it be possible for this feature to be added in the long term? In the meantime, is there a method of calling C++ functions from Dask-awkward?

Thanks!

James Catmore (ATLAS)

**Comment by martindurant** [comment]
cc @jpivarski 

The simple solution, is that you can call that method (the ak version) on each partition of a dask-dataframe (`.map_partitions`). So what should a pile of RDataFrames do, though? It would no longer be a dask-awkward array, I suppose.

**Comment by douglasdavis** [comment]
Something like this may work; (with an explicit argument for optimizing the _awkward_ collection because of course once we leave awkward we can't use dask-awkward optimizations back).

```python
class ToRDataFrame:
    def __init__(self, keys: Sequence[str], flatlist_as_rvec: bool = True) -> None:
        self.keys = keys
        self.flatlist_as_rvec = flatlist_as_rvec

    def __call__(*args: ak.Array) -> Any:
        array_dict = {k: p for k, p in zip(self.keys, list(args))}
        return ak.to_rdataframe(array_dict, flatlist_as_rvec=self.flatlist_as_rvec)


def to_rdataframe(
    arrays: dict[str, dak.Array],
    *,
    flatlist_as_rvec: bool = True,
    optimize_graph: bool = False,
):
    keys, colls = [], []
    for k, coll in arrays.items():
        keys.append(k)
        if optimize_graph:
            colls.append(dask.optimize(coll)[0])
        else:
            colls.append(coll)

    fn = ToRDataFrame(keys, flatlist_as_rvec=flatlist_as_rvec)

    mp_res = map_partitions(
        fn,
        *colls,
        label="to-rdataframe",
        meta=empty_typetracer(),
    )

    return dak.to_delayed(mp_res)
```

**Comment by douglasdavis** [comment]
invoking ak.to_rdataframe does some ROOT importing/setup:

```
In [1]: import awkward._connect.rdataframe.to_rdataframe
Installed ROOT event loop hook.
```

If we don't pre-import this the dask compute hangs; We can do this explicitly when `dak.to_rdataframe` is called and with the default (threaded) scheduler things then work, but I wonder if this will cause a problem on distributed workers

**Comment by jpivarski** [comment]
> So what should a pile of RDataFrames do, though? It would no longer be a dask-awkward array, I suppose.

`ak.to_rdataframe` returns something that is no longer an Awkward Array, but it might be a Dask object. RDataFrame has a Distributed mode that runs on Spark and Dask ([ref](https://root.cern/blog/distributed-rdataframe/), [ref](https://indico.fnal.gov/event/23628/contributions/240608/attachments/154873/201557/distributed_RDF_padulano_ROOT_workshop_2022.pdf), [ref](https://iopscience.iop.org/article/10.1088/1742-6596/2438/1/012097/pdf), [ref](https://www.epj-conferences.org/articles/epjconf/pdf/2020/21/epjconf_chep2020_03009.pdf)). What I don't know is whether that mode "takes over" and drives Dask, or whether it's a Dask collection that can be used with other Dask collections. I suspect the former, and if so, then perhaps we can't mix distributed-Awkward with distributed-RDataFrame through `dak.to_rdataframe`.

We can run Numba-accelerated code on the workers, in part because it's just a function call in which Awkward Arrays can be arguments and/or return values.

The C++ equivalent of Numba is not RDataFrame, but cppyy. The Awkward-cppyy interface works like the Awkward-Numba interface: Awkward Arrays can be arguments and/or return values of functions, but instead of being Numba-accelerated Python functions, they're C++ functions.

This was added in the past year; [here's a paper](https://indico.jlab.org/event/459/contributions/11557/) (I don't know what happened to the talk slides) and there's a code example in [this talk](https://indico.jlab.org/event/459/contributions/11579/) (page 12):

```python
array = ak.Array([
    [{"x": 1, "y": [1.1]}, {"x": 2, "y": [2.2, 0.2]}],
    [],
    [{"x": 3, "y": [3.0, 0.3, 3.3]}],
])

source_code_cpp = """
template <typename T>
double go_fast_cpp(T& awkward_array) {
    double out = 0.0;
    for (auto list : awkward_array) {
        for (auto record : list) {
            for (auto item : record.y()) {
                out += item;
            }
        }
    }
    return out;
}
"""
cppyy.cppdef(source_code_cpp)

out = cppyy.gbl.go_fast_cpp[array.cpp_type](array)
assert out == ak.sum(array["y"])
```

(The Awkward Array's C++ type is sufficiently complicated that we want to hide it in a template parameter and instantiate that template parameter with `array.cpp_type`.)

I think this would be a better interface to approach for distributing C++ on Awkward Arrays in Dask. RDataFrame is higher level and tries to control too much about how it gets parallelized—for user convenience, but at a cost to composability. Raw function calls are infinitely composable and would be much easier to fit into the context of another system that controls parallel-processing.

Cc: @ianna

> invoking ak.to_rdataframe does some ROOT importing/setup:
> 
> ```
> In [1]: import awkward._connect.rdataframe.to_rdataframe
> Installed ROOT event loop hook.
> ```

Both the Awkward-RDataFrame bridge and the Awkward-cppyy bridge compile some code the first time an `ak.Array` is used in a function and additional code as needed. I don't see why that would be a problem for Dask workers—each Dask worker is a process and has to independently compile the upfront code on first usage, just as it does outside of a Dask worker. I hope that the JIT-compilation step applies a lock to ensure thread-safety (only one thread per process should do the compilation, and thereafter it's read-only). If the JIT-compilation step is not thread-safe yet, we can test it with `--nthreads 1`.

Also, I've never seen this

```
Installed ROOT event loop hook.
```

(I tried the import just now.) Does it really print that? Is ROOT the one that's generating the message? I don't see it in the Awkward codebase. I'm not asking just because of the stdout verbiage, but because of what it might be doing.

**Comment by agoose77** [comment]
I think that's a PyROOT thing that happens inside an IPython context.

**Comment by jcatmore** [comment]
Hi,

thanks for the quick response and sorry for my late reply.

As a quick test to get started I tried to run the code snippet posted by @jpivarski (which I'd actually seen earlier from some CHEP slides). On my installation there is a attribute crash on this line:

`out = cppyy.gbl.go_fast_cpp[array.cpp_type](array)`

which looks like this:

`
~/.local/lib/python3.9/site-packages/awkward/cppyy.py in register_and_check()
     26 
     27     if not _has_checked_version:
---> 28         if ak._util.parse_version(cppyy.__version__) < ak._util.parse_version("3.0.1"):
     29             raise ImportError(
     30                 "Awkward Array can only work with cppyy 3.0.1 or later "

AttributeError: module 'awkward._util' has no attribute 'parse_version'
` 

Do I need to use an experimental version of either AA or cppyy? Currently I have:

`
import awkward as ak
print(ak.__version__)
--> 2.4.3
import cppyy 
print(cppyy.__version__)
--> 1.6.2
`

I see the latter is much earlier than 3.0.1, although this version isn't available via PyPI: the latest available version seems to be 3.0.0.

Thanks!

James.

**Comment by jpivarski** [comment]
If ROOT is in the Python environment (i.e. in `sys.path`), then ROOT's cppyy overshadows an individually installed one. This is a problem that will likely only be solved by changing cppyy's name.

But about 3.0.0 being the latest release—I need to check into that. The updates needed by Awkward were added many months ago—I would have thought that 3.0.1 would be out by now.

**Comment by jcatmore** [comment]
I tried again without ROOT in the environment, and then the version number for cppyy went to the expected 3.0.0:
```
import cppyy 
print(cppyy.__version__)
-->(Re-)building pre-compiled headers (options: -O2 -march=native); this may take a minute ...
3.0.0
```

Awkward version remains as `2.4.3`. However, I still get the same error message when trying the snippet posted above:

```
AttributeError: module 'awkward._util' has no attribute 'parse_version'
```

**Comment by jpivarski** [comment]
Perhaps the best way to ask about the 3.0.1 cppyy release is to ask @wlav and @ianna.

@ianna, what was the reason that Awkward's cppyy bridge needs 3.0.1? You added something to cppyy to allow it to register Awkward types, in a sense that's similar to Numba's registration, right? ([I don't see any PRs](https://github.com/wlav/cppyy/pulls?q=+is%3Apr+author%3Aianna+), so maybe it was contributed upstream of GitHub?)

@wlav, is there any chance that a 3.0.1 could be released with at least or only that feature?

Thanks!

**Comment by ianna** [comment]
> Perhaps the best way to ask about the 3.0.1 cppyy release is to ask @wlav and @ianna.
> 
> @ianna, what was the reason that Awkward's cppyy bridge needs 3.0.1? You added something to cppyy to allow it to register Awkward types, in a sense that's similar to Numba's registration, right? ([I don't see any PRs](https://github.com/wlav/cppyy/pulls?q=+is%3Apr+author%3Aianna+), so maybe it was contributed upstream of GitHub?)
> 
> @wlav, is there any chance that a 3.0.1 could be released with at least or only that feature?
> 
> Thanks!

the reason why we want 3.1 is that implements an implicit conversion from a tuple of arguments where we have a templated type.

**Comment by jcatmore** [comment]
Hi @jpivarski @ianna ,

just to confirm that with the latest version of awkward and cppyy (3.1.2) the example from Jim above works perfectly! 

I think we can close this feature request because it isn't so relevant if cppyy is working. I'll play with it a bit and if I encounter any problems I'll file a different feature request or bug report in the appropriate repo.

Thanks, and wishing you a happy holiday season when it arrives!

James.
